export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/users/me',
    institutions: '/auth/institutions',
    switchInstitution: '/auth/switch-institution',
  },
  institutions: {
    public: '/institutions/public',
    current: '/institutions/current',
    campuses: '/institutions/campuses',
    campus: (id: number) => `/institutions/campuses/${id}`,
  },
  platform: {
    institutions: '/platform/institutions',
    institution: (id: number) => `/platform/institutions/${id}`,
  },
  academic: {
    units: '/academic/units',
    unit: (id: number) => `/academic/units/${id}`,
    programs: '/academic/programs',
    program: (id: number) => `/academic/programs/${id}`,
    programCurricula: (programId: number) => `/academic/programs/${programId}/curricula`,
    subjects: '/academic/subjects',
    subject: (id: number) => `/academic/subjects/${id}`,
    prerequisites: (subjectId: number) => `/academic/subjects/${subjectId}/prerequisites`,
    prerequisite: (subjectId: number, requiredId: number) => `/academic/subjects/${subjectId}/prerequisites/${requiredId}`,
    equivalences: (subjectId: number) => `/academic/subjects/${subjectId}/equivalences`,
    equivalence: (subjectId: number, otherId: number) => `/academic/subjects/${subjectId}/equivalences/${otherId}`,
    curriculum: (id: number) => `/academic/curricula/${id}`,
    curriculumActivate: (id: number) => `/academic/curricula/${id}/activate`,
    curriculumArchive: (id: number) => `/academic/curricula/${id}/archive`,
    curriculumVersions: (id: number) => `/academic/curricula/${id}/versions`,
    curriculumComponents: (id: number) => `/academic/curricula/${id}/components`,
    component: (id: number) => `/academic/curriculum-components/${id}`,
    terms: '/academic/terms',
    term: (id: number) => `/academic/terms/${id}`,
    termStatus: (id: number) => `/academic/terms/${id}/status`,
    termCalendarSummary: (id: number) => `/academic/terms/${id}/calendar-summary`,
    gradingPeriods: (termId: number) => `/academic/terms/${termId}/grading-periods`,
    gradingPeriod: (id: number) => `/academic/grading-periods/${id}`,
    gradingPeriodStatus: (id: number) => `/academic/grading-periods/${id}/status`,
    calendarEvents: '/academic/calendar-events',
    calendarEvent: (id: number) => `/academic/calendar-events/${id}`,
    programEnrollments: '/academic/program-enrollments',
    programEnrollmentStatus: (id: number) => `/academic/program-enrollments/${id}/status`,
    classGroups: '/academic/class-groups',
    classGroup: (id: number) => `/academic/class-groups/${id}`,
    classGroupMembers: (id: number) => `/academic/class-groups/${id}/members`,
    classGroupMember: (id: number, enrollmentId: number) => `/academic/class-groups/${id}/members/${enrollmentId}`,
  },
  assessment: {
    schemes: '/assessment/grading-schemes',
    scheme: (id: number) => `/assessment/grading-schemes/${id}`,
    teachingOfferings: '/assessment/teaching/offerings',
    offering: (id: number) => `/assessment/offerings/${id}`,
    syncGroup: (id: number) => `/assessment/offerings/${id}/sync-group-enrollments`,
    items: (offeringId: number) => `/assessment/offerings/${offeringId}/items`,
    item: (id: number) => `/assessment/items/${id}`,
    grades: (itemId: number) => `/assessment/items/${itemId}/grades`,
    importQuiz: (itemId: number) => `/assessment/items/${itemId}/import-quiz`,
    gradebook: (offeringId: number) => `/assessment/offerings/${offeringId}/gradebook`,
    diary: (offeringId: number) => `/assessment/offerings/${offeringId}/diary`,
    diaryEntry: (id: number) => `/assessment/diary-entries/${id}`,
    diaryAttendance: (id: number) => `/assessment/diary-entries/${id}/attendance`,
    closePeriod: (offeringId: number, periodId: number) => `/assessment/offerings/${offeringId}/periods/${periodId}/close`,
    results: (offeringId: number) => `/assessment/offerings/${offeringId}/results`,
    computeResults: (offeringId: number) => `/assessment/offerings/${offeringId}/results/compute`,
    recovery: (offeringId: number) => `/assessment/offerings/${offeringId}/recovery`,
    finalize: (offeringId: number) => `/assessment/offerings/${offeringId}/finalize`,
    myReportCard: '/assessment/my/report-card',
  },
  courses: {
    list: '/courses',
    detail: (id: number) => `/courses/${id}`,
    lessons: (courseId: number) => `/lessons/course/${courseId}`,
    modules: (courseId: number) => `/courses/${courseId}/modules`,
    moduleDetail: (moduleId: number) => `/courses/modules/${moduleId}`,
    prerequisites: (courseId: number) => `/courses/${courseId}/prerequisites`,
  },
  learningPaths: {
    list: '/learning-paths',
    detail: (id: number) => `/learning-paths/${id}`,
    courses: (id: number) => `/learning-paths/${id}/courses`,
  },
  enrollments: {
    byStudent: (studentId: number) => `/enrollments/student/${studentId}`,
    create: '/enrollments',
  },
  progress: {
    me: '/progress/me',
    courses: '/progress/me/courses',
    update: (lessonId: number) => `/progress/${lessonId}`,
  },
  sessions: {
    me: '/sessions/me',
    history: '/sessions/me/history',
    create: '/sessions',
    voiceStart: '/sessions/voice/start',
    voice: (id: number) => `/sessions/${id}/voice`,
  },
  schedule: {
    locations: '/schedule/locations',
    location: (id: number) => `/schedule/locations/${id}`,
    rooms: '/schedule/rooms',
    room: (id: number) => `/schedule/rooms/${id}`,
    classes: '/schedule/classes',
    class: (id: number) => `/schedule/classes/${id}`,
    classMeetings: (id: number) => `/schedule/classes/${id}/meetings`,
    classEnrollments: (id: number) => `/schedule/classes/${id}/enrollments`,
    classWaitlist: (id: number) => `/schedule/classes/${id}/waitlist`,
    joinClass: (id: number) => `/schedule/classes/${id}/join`,
    instructorAgenda: (id: number) => `/schedule/instructors/${id}/agenda`,
    meetings: '/schedule/meetings',
    meeting: (id: number) => `/schedule/meetings/${id}`,
    closeMeeting: (id: number) => `/schedule/meetings/${id}/close`,
    meetingSummary: (id: number) => `/schedule/meetings/${id}/summary`,
    checkinTokens: (meetingId: number) => `/schedule/meetings/${meetingId}/checkin-tokens`,
    checkIn: (token: string) => `/schedule/check-in/${token}`,
    attendance: (meetingId: number) => `/schedule/meetings/${meetingId}/attendance`,
    attendanceReport: (meetingId: number) => `/schedule/meetings/${meetingId}/attendance-report`,
    practicalAssessments: (meetingId: number) => `/schedule/meetings/${meetingId}/practical-assessments`,
  },
  certificates: {
    rule: (courseId: number) => `/certificates/rules/${courseId}`,
    eligibility: (courseId: number, studentId: number) => `/certificates/courses/${courseId}/students/${studentId}/eligibility`,
    issue: (courseId: number, studentId: number) => `/certificates/courses/${courseId}/students/${studentId}/issue`,
    courseCertificates: (courseId: number) => `/certificates/courses/${courseId}/certificates`,
    revoke: (id: number) => `/certificates/${id}/revoke`,
    download: (id: number) => `/certificates/${id}/download`,
    validate: (code: string) => `/certificates/validate/${code}`,
    my: '/certificates/students/me',
    student: (studentId: number) => `/certificates/students/${studentId}`,
  },
  notifications: {
    templates: '/notifications/templates',
    template: (key: string, channel: string) => `/notifications/templates/${key}/${channel}`,
    events: '/notifications/events',
    processDue: '/notifications/events/process-due',
    eventSent: (id: number) => `/notifications/events/${id}/mark-sent`,
    eventFailed: (id: number) => `/notifications/events/${id}/mark-failed`,
  },
  lessons: {
    videoStream: (id: number) => `/lessons/${id}/video/stream`,
    videoUpload: (id: number) => `/lessons/${id}/video`,
  },
  assignments: {
    mine: (lessonId: number) => `/assignments/lessons/${lessonId}/me`,
    submit: (lessonId: number) => `/assignments/lessons/${lessonId}/submit`,
    submissions: (lessonId: number) => `/assignments/lessons/${lessonId}/submissions`,
    review: (submissionId: number) => `/assignments/submissions/${submissionId}`,
    download: (submissionId: number) => `/assignments/submissions/${submissionId}/download`,
  },
  quizzes: {
    lesson: (lessonId: number) => `/quizzes/lesson/${lessonId}`,
    lessonOptional: (lessonId: number) => `/quizzes/lesson/${lessonId}/optional`,
    attempts: (lessonId: number) => `/quizzes/lesson/${lessonId}/attempts`,
    attemptsOptional: (lessonId: number) => `/quizzes/lesson/${lessonId}/attempts/optional`,
    attempt: (lessonId: number) => `/quizzes/lesson/${lessonId}/attempt`,
  },
  finance: {
    plans: '/finance/plans',
    plan: (id: number) => `/finance/plans/${id}`,
    subscriptions: '/finance/subscriptions',
    subscription: (id: number) => `/finance/subscriptions/${id}`,
    charges: '/finance/charges',
    charge: (id: number) => `/finance/charges/${id}`,
    chargeAsaas: (id: number) => `/finance/charges/${id}/gateway/asaas`,
    chargePaid: (id: number) => `/finance/charges/${id}/paid`,
    chargeFailed: (id: number) => `/finance/charges/${id}/failed`,
  },
  analytics: {
    overview: '/analytics/overview',
    courses: '/analytics/courses',
    course: (id: number) => `/analytics/courses/${id}`,
    me: '/analytics/students/me',
    student: (id: number) => `/analytics/students/${id}`,
    class: (id: number) => `/analytics/classes/${id}`,
    reports: {
      completion: '/analytics/reports/completion',
      attendance: '/analytics/reports/attendance',
      engagement: '/analytics/reports/engagement',
      performance: '/analytics/reports/performance',
      roi: '/analytics/reports/roi',
    },
  },
  documents: {
    list: '/documents',
    detail: (id: number) => `/documents/${id}`,
    versions: (id: number) => `/documents/${id}/versions`,
    versionDownload: (documentId: number, versionId: number) => `/documents/${documentId}/versions/${versionId}/download`,
    download: (id: number) => `/documents/${id}/download`,
  },
  forum: {
    courseThreads: (courseId: number) => `/forum/courses/${courseId}/threads`,
    thread: (threadId: number) => `/forum/threads/${threadId}`,
    posts: (threadId: number) => `/forum/threads/${threadId}/posts`,
  },
  chat: {
    conversations: '/chat/conversations',
    conversation: (id: number) => `/chat/conversations/${id}`,
    messages: (id: number) => `/chat/conversations/${id}/messages`,
  },
};
