export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/users/me',
    institutions: '/auth/institutions',
    switchInstitution: '/auth/switch-institution',
  },
  institutions: {
    public: '/institutions/public',
    current: '/institutions/current',
    campuses: '/institutions/campuses',
    campus: (id: string) => `/institutions/campuses/${id}`,
  },
  platform: {
    institutions: '/platform/institutions',
    institution: (id: string) => `/platform/institutions/${id}`,
  },
  academic: {
    units: '/academic/units',
    unit: (id: string) => `/academic/units/${id}`,
    programs: '/academic/programs',
    program: (id: string) => `/academic/programs/${id}`,
    programCurricula: (programId: string) => `/academic/programs/${programId}/curricula`,
    subjects: '/academic/subjects',
    subject: (id: string) => `/academic/subjects/${id}`,
    prerequisites: (subjectId: string) => `/academic/subjects/${subjectId}/prerequisites`,
    prerequisite: (subjectId: string, requiredId: string) => `/academic/subjects/${subjectId}/prerequisites/${requiredId}`,
    equivalences: (subjectId: string) => `/academic/subjects/${subjectId}/equivalences`,
    equivalence: (subjectId: string, otherId: string) => `/academic/subjects/${subjectId}/equivalences/${otherId}`,
    curriculum: (id: string) => `/academic/curricula/${id}`,
    curriculumActivate: (id: string) => `/academic/curricula/${id}/activate`,
    curriculumArchive: (id: string) => `/academic/curricula/${id}/archive`,
    curriculumVersions: (id: string) => `/academic/curricula/${id}/versions`,
    curriculumComponents: (id: string) => `/academic/curricula/${id}/components`,
    component: (id: string) => `/academic/curriculum-components/${id}`,
    terms: '/academic/terms',
    term: (id: string) => `/academic/terms/${id}`,
    termStatus: (id: string) => `/academic/terms/${id}/status`,
    termCalendarSummary: (id: string) => `/academic/terms/${id}/calendar-summary`,
    gradingPeriods: (termId: string) => `/academic/terms/${termId}/grading-periods`,
    gradingPeriod: (id: string) => `/academic/grading-periods/${id}`,
    gradingPeriodStatus: (id: string) => `/academic/grading-periods/${id}/status`,
    calendarEvents: '/academic/calendar-events',
    calendarEvent: (id: string) => `/academic/calendar-events/${id}`,
    programEnrollments: '/academic/program-enrollments',
    programEnrollmentStatus: (id: string) => `/academic/program-enrollments/${id}/status`,
    classGroups: '/academic/class-groups',
    classGroup: (id: string) => `/academic/class-groups/${id}`,
    classGroupMembers: (id: string) => `/academic/class-groups/${id}/members`,
    classGroupMember: (id: string, enrollmentId: string) => `/academic/class-groups/${id}/members/${enrollmentId}`,
  },
  assessment: {
    schemes: '/assessment/grading-schemes',
    scheme: (id: string) => `/assessment/grading-schemes/${id}`,
    teachingOfferings: '/assessment/teaching/offerings',
    offering: (id: string) => `/assessment/offerings/${id}`,
    syncGroup: (id: string) => `/assessment/offerings/${id}/sync-group-enrollments`,
    items: (offeringId: string) => `/assessment/offerings/${offeringId}/items`,
    item: (id: string) => `/assessment/items/${id}`,
    grades: (itemId: string) => `/assessment/items/${itemId}/grades`,
    importQuiz: (itemId: string) => `/assessment/items/${itemId}/import-quiz`,
    gradebook: (offeringId: string) => `/assessment/offerings/${offeringId}/gradebook`,
    diary: (offeringId: string) => `/assessment/offerings/${offeringId}/diary`,
    diaryEntry: (id: string) => `/assessment/diary-entries/${id}`,
    diaryAttendance: (id: string) => `/assessment/diary-entries/${id}/attendance`,
    closePeriod: (offeringId: string, periodId: string) => `/assessment/offerings/${offeringId}/periods/${periodId}/close`,
    results: (offeringId: string) => `/assessment/offerings/${offeringId}/results`,
    computeResults: (offeringId: string) => `/assessment/offerings/${offeringId}/results/compute`,
    recovery: (offeringId: string) => `/assessment/offerings/${offeringId}/recovery`,
    finalize: (offeringId: string) => `/assessment/offerings/${offeringId}/finalize`,
    myReportCard: '/assessment/my/report-card',
  },
  secretariat: {
    students: '/secretariat/students',
    enrollment: (id: string) => `/secretariat/enrollments/${id}`,
    action: (id: string, action: string) => `/secretariat/enrollments/${id}/${action}`,
    registrations: (id: string) => `/secretariat/enrollments/${id}/registrations`,
    events: (id: string) => `/secretariat/enrollments/${id}/events`,
    creditTransfers: (id: string) => `/secretariat/enrollments/${id}/credit-transfers`,
    creditDecision: (transferId: string) => `/secretariat/credit-transfers/${transferId}/decision`,
    transcript: (id: string) => `/secretariat/enrollments/${id}/transcript`,
    myTranscripts: '/secretariat/my/transcripts',
    declarations: (id: string) => `/secretariat/enrollments/${id}/declarations`,
    declarationPdf: (declarationId: string) => `/secretariat/declarations/${declarationId}/pdf`,
    declarationRevoke: (declarationId: string) => `/secretariat/declarations/${declarationId}/revoke`,
    validateDeclaration: (code: string) => `/secretariat/declarations/validate/${encodeURIComponent(code)}`,
    myDeclarations: '/secretariat/my/declarations',
    myDeclarationPdf: (declarationId: string) => `/secretariat/my/declarations/${declarationId}/pdf`,
    conclusion: (id: string) => `/secretariat/enrollments/${id}/conclusion`,
    ceremony: (id: string) => `/secretariat/enrollments/${id}/ceremony`,
  },
  guardians: {
    links: (studentId: string) => `/guardians/students/${studentId}/links`,
    link: (linkId: string) => `/guardians/links/${linkId}`,
    dependents: '/guardians/me/dependents',
    reportCard: (studentId: string) => `/guardians/me/dependents/${studentId}/report-card`,
    notices: (studentId: string) => `/guardians/me/dependents/${studentId}/notices`,
    charges: (studentId: string) => `/guardians/me/dependents/${studentId}/charges`,
    occurrences: (studentId: string) => `/guardians/me/dependents/${studentId}/occurrences`,
    acknowledge: (studentId: string, occurrenceId: string) => `/guardians/me/dependents/${studentId}/occurrences/${occurrenceId}/acknowledge`,
    agenda: (studentId: string) => `/guardians/me/dependents/${studentId}/agenda`,
  },
  school: {
    occurrences: '/school/occurrences',
    occurrence: (occurrenceId: string) => `/school/occurrences/${occurrenceId}`,
    studentOccurrences: (studentId: string) => `/school/students/${studentId}/occurrences`,
    groupAgenda: (groupId: string) => `/school/class-groups/${groupId}/agenda`,
    agendaItem: (itemId: string) => `/school/agenda/${itemId}`,
    myAgenda: '/school/my/agenda',
  },
  registration: {
    windows: '/registration/windows',
    window: (id: string) => `/registration/windows/${id}`,
    offeringSlots: (offeringId: string) => `/registration/offerings/${offeringId}/time-slots`,
    slot: (id: string) => `/registration/time-slots/${id}`,
    myWindows: '/registration/my/windows',
    myCatalog: (windowId: string) => `/registration/my/windows/${windowId}/catalog`,
    myOffering: (windowId: string, offeringId: string) => `/registration/my/windows/${windowId}/offerings/${offeringId}`,
    officeCatalog: (enrollmentId: string, termId: string) => `/registration/program-enrollments/${enrollmentId}/terms/${termId}/catalog`,
    officeOffering: (enrollmentId: string, offeringId: string) => `/registration/program-enrollments/${enrollmentId}/offerings/${offeringId}`,
  },
  completion: {
    integralization: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/integralization`,
    myIntegralization: '/completion/my/integralization',
    activities: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/activities`,
    activityDecision: (activityId: string) => `/completion/activities/${activityId}/decision`,
    myActivities: '/completion/my/activities',
    submitActivity: (enrollmentId: string) => `/completion/my/enrollments/${enrollmentId}/activities`,
    myActivity: (activityId: string) => `/completion/my/activities/${activityId}`,
    internships: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/internships`,
    internship: (internshipId: string) => `/completion/internships/${internshipId}`,
    myInternships: '/completion/my/internships',
    internshipLogs: (internshipId: string) => `/completion/internships/${internshipId}/logs`,
    addInternshipLog: (internshipId: string) => `/completion/my/internships/${internshipId}/logs`,
    myInternshipLog: (logId: string) => `/completion/my/internship-logs/${logId}`,
    reviewLog: (logId: string) => `/completion/internship-logs/${logId}/review`,
    finalProject: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/final-project`,
    finalProjectResult: (projectId: string) => `/completion/final-projects/${projectId}/result`,
    myFinalProjects: '/completion/my/final-projects',
    advising: '/completion/advising',
    advisors: '/completion/advisors',
  },
  tuition: {
    plans: '/tuition/plans',
    plan: (id: string) => `/tuition/plans/${id}`,
    generate: (id: string) => `/tuition/plans/${id}/generate`,
    settings: '/tuition/settings',
    discounts: (enrollmentId: string) => `/tuition/enrollments/${enrollmentId}/discounts`,
    deactivateDiscount: (id: string) => `/tuition/discounts/${id}/deactivate`,
    statement: (enrollmentId: string) => `/tuition/enrollments/${enrollmentId}/charges`,
    myCharges: '/tuition/my/charges',
    quote: (chargeId: string) => `/tuition/charges/${chargeId}/quote`,
    settle: (chargeId: string) => `/tuition/charges/${chargeId}/settle`,
  },
  contracts: {
    templates: '/contracts/templates',
    template: (id: string) => `/contracts/templates/${id}`,
    enrollment: (enrollmentId: string) => `/contracts/enrollments/${enrollmentId}`,
    cancel: (id: string) => `/contracts/${id}/cancel`,
    pdf: (id: string) => `/contracts/${id}/pdf`,
    mine: '/contracts/my',
    myPdf: (id: string) => `/contracts/my/${id}/pdf`,
    accept: (id: string) => `/contracts/my/${id}/accept`,
    validate: (code: string) => `/contracts/validate/${encodeURIComponent(code)}`,
  },
  saas: {
    plans: '/saas/plans',
    plan: (id: string) => `/saas/plans/${id}`,
    institution: (id: string) => `/saas/institutions/${id}`,
    subscription: (id: string) => `/saas/institutions/${id}/subscription`,
    invoices: (id: string) => `/saas/institutions/${id}/invoices`,
    invoicePaid: (id: string) => `/saas/invoices/${id}/paid`,
    current: '/saas/current',
  },
  admissions: {
    publicCalls: '/admissions/public/calls',
    publicCall: (id: string) => `/admissions/public/calls/${id}`,
    publicResult: (id: string) => `/admissions/public/calls/${id}/result`,
    apply: (callId: string) => `/admissions/calls/${callId}/apply`,
    mine: '/admissions/my/applications',
    myDocuments: (id: string) => `/admissions/my/applications/${id}/documents`,
    myAction: (id: string, action: 'withdraw' | 'confirm' | 'decline') => `/admissions/my/applications/${id}/${action}`,
    calls: '/admissions/calls',
    call: (id: string) => `/admissions/calls/${id}`,
    callStatus: (id: string) => `/admissions/calls/${id}/status`,
    callApplications: (id: string) => `/admissions/calls/${id}/applications`,
    review: (applicationId: string) => `/admissions/applications/${applicationId}/review`,
    documentReview: (documentId: string) => `/admissions/documents/${documentId}/review`,
    documentDownload: (documentId: string) => `/admissions/documents/${documentId}/download`,
    select: (id: string) => `/admissions/calls/${id}/select`,
    deadlines: (id: string) => `/admissions/calls/${id}/process-deadlines`,
  },
  social: {
    fundingSources: '/social/funding-sources',
    fundingSource: (id: string) => `/social/funding-sources/${id}`,
    fundingReport: (id: string) => `/social/funding-sources/${id}/report`,
    fundingReportCsv: (id: string) => `/social/funding-sources/${id}/report.csv`,
    items: '/social/benefit-items',
    item: (id: string) => `/social/benefit-items/${id}`,
    stock: (itemId: string) => `/social/benefit-items/${itemId}/stock`,
    meetingDeliveries: (meetingId: string) => `/social/meetings/${meetingId}/deliveries`,
    deliveries: '/social/deliveries',
    offeringDeliveries: (offeringId: string) => `/social/offerings/${offeringId}/deliveries`,
    myBenefits: '/social/my/benefits',
  },
  retention: {
    offering: (offeringId: string) => `/retention/offerings/${offeringId}`,
    evaluate: (offeringId: string) => `/retention/offerings/${offeringId}/evaluate`,
    readmit: (enrollmentId: string) => `/retention/enrollments/${enrollmentId}/readmit`,
  },
  access: {
    me: '/access/me',
    permissions: '/access/permissions',
    builtIn: '/access/built-in',
    members: '/access/members',
    roles: '/access/roles',
    role: (id: string) => `/access/roles/${id}`,
    roleMembers: (id: string) => `/access/roles/${id}/members`,
    roleMember: (id: string, userId: string) => `/access/roles/${id}/members/${userId}`,
  },
  warehouse: {
    items: '/warehouse/items',
    item: (id: string) => `/warehouse/items/${id}`,
    entries: (id: string) => `/warehouse/items/${id}/entries`,
    requests: '/warehouse/requests',
    myRequests: '/warehouse/my/requests',
    cancel: (id: string) => `/warehouse/my/requests/${id}/cancel`,
    action: (id: string, action: 'approve' | 'reject' | 'deliver' | 'returns') => `/warehouse/requests/${id}/${action}`,
    lowStock: '/warehouse/reports/low-stock',
    overdue: '/warehouse/reports/overdue',
    consumption: '/warehouse/reports/consumption',
  },
  courses: {
    list: '/courses',
    detail: (id: string) => `/courses/${id}`,
    lessons: (courseId: string) => `/lessons/course/${courseId}`,
    modules: (courseId: string) => `/courses/${courseId}/modules`,
    moduleDetail: (moduleId: string) => `/courses/modules/${moduleId}`,
    prerequisites: (courseId: string) => `/courses/${courseId}/prerequisites`,
  },
  learningPaths: {
    list: '/learning-paths',
    detail: (id: string) => `/learning-paths/${id}`,
    courses: (id: string) => `/learning-paths/${id}/courses`,
  },
  enrollments: {
    byStudent: (studentId: string) => `/enrollments/student/${studentId}`,
    create: '/enrollments',
  },
  progress: {
    me: '/progress/me',
    courses: '/progress/me/courses',
    update: (lessonId: string) => `/progress/${lessonId}`,
  },
  sessions: {
    me: '/sessions/me',
    history: '/sessions/me/history',
    create: '/sessions',
    voiceStart: '/sessions/voice/start',
    voice: (id: string) => `/sessions/${id}/voice`,
  },
  schedule: {
    locations: '/schedule/locations',
    location: (id: string) => `/schedule/locations/${id}`,
    rooms: '/schedule/rooms',
    room: (id: string) => `/schedule/rooms/${id}`,
    classes: '/schedule/classes',
    class: (id: string) => `/schedule/classes/${id}`,
    classMeetings: (id: string) => `/schedule/classes/${id}/meetings`,
    classEnrollments: (id: string) => `/schedule/classes/${id}/enrollments`,
    classWaitlist: (id: string) => `/schedule/classes/${id}/waitlist`,
    joinClass: (id: string) => `/schedule/classes/${id}/join`,
    instructorAgenda: (id: string) => `/schedule/instructors/${id}/agenda`,
    meetings: '/schedule/meetings',
    meeting: (id: string) => `/schedule/meetings/${id}`,
    closeMeeting: (id: string) => `/schedule/meetings/${id}/close`,
    meetingSummary: (id: string) => `/schedule/meetings/${id}/summary`,
    checkinTokens: (meetingId: string) => `/schedule/meetings/${meetingId}/checkin-tokens`,
    checkIn: (token: string) => `/schedule/check-in/${token}`,
    attendance: (meetingId: string) => `/schedule/meetings/${meetingId}/attendance`,
    attendanceReport: (meetingId: string) => `/schedule/meetings/${meetingId}/attendance-report`,
    practicalAssessments: (meetingId: string) => `/schedule/meetings/${meetingId}/practical-assessments`,
  },
  certificates: {
    rule: (courseId: string) => `/certificates/rules/${courseId}`,
    eligibility: (courseId: string, studentId: string) => `/certificates/courses/${courseId}/students/${studentId}/eligibility`,
    issue: (courseId: string, studentId: string) => `/certificates/courses/${courseId}/students/${studentId}/issue`,
    courseCertificates: (courseId: string) => `/certificates/courses/${courseId}/certificates`,
    revoke: (id: string) => `/certificates/${id}/revoke`,
    download: (id: string) => `/certificates/${id}/download`,
    validate: (code: string) => `/certificates/validate/${code}`,
    my: '/certificates/students/me',
    student: (studentId: string) => `/certificates/students/${studentId}`,
  },
  notifications: {
    templates: '/notifications/templates',
    template: (key: string, channel: string) => `/notifications/templates/${key}/${channel}`,
    events: '/notifications/events',
    processDue: '/notifications/events/process-due',
    eventRetry: (id: string) => `/notifications/events/${id}/retry`,
    inbox: '/notifications/me',
    inboxSummary: '/notifications/me/summary',
    inboxReadAll: '/notifications/me/read-all',
    inboxRead: (id: string) => `/notifications/me/${id}/read`,
  },
  lessons: {
    videoStream: (id: string) => `/lessons/${id}/video/stream`,
    videoUpload: (id: string) => `/lessons/${id}/video`,
  },
  assignments: {
    mine: (lessonId: string) => `/assignments/lessons/${lessonId}/me`,
    submit: (lessonId: string) => `/assignments/lessons/${lessonId}/submit`,
    submissions: (lessonId: string) => `/assignments/lessons/${lessonId}/submissions`,
    review: (submissionId: string) => `/assignments/submissions/${submissionId}`,
    download: (submissionId: string) => `/assignments/submissions/${submissionId}/download`,
  },
  quizzes: {
    lesson: (lessonId: string) => `/quizzes/lesson/${lessonId}`,
    lessonOptional: (lessonId: string) => `/quizzes/lesson/${lessonId}/optional`,
    attempts: (lessonId: string) => `/quizzes/lesson/${lessonId}/attempts`,
    attemptsOptional: (lessonId: string) => `/quizzes/lesson/${lessonId}/attempts/optional`,
    attempt: (lessonId: string) => `/quizzes/lesson/${lessonId}/attempt`,
  },
  finance: {
    plans: '/finance/plans',
    plan: (id: string) => `/finance/plans/${id}`,
    subscriptions: '/finance/subscriptions',
    subscription: (id: string) => `/finance/subscriptions/${id}`,
    charges: '/finance/charges',
    charge: (id: string) => `/finance/charges/${id}`,
    chargeAsaas: (id: string) => `/finance/charges/${id}/gateway/asaas`,
    chargePaid: (id: string) => `/finance/charges/${id}/paid`,
    chargeFailed: (id: string) => `/finance/charges/${id}/failed`,
  },
  analytics: {
    overview: '/analytics/overview',
    courses: '/analytics/courses',
    course: (id: string) => `/analytics/courses/${id}`,
    me: '/analytics/students/me',
    student: (id: string) => `/analytics/students/${id}`,
    class: (id: string) => `/analytics/classes/${id}`,
    reports: {
      completion: '/analytics/reports/completion',
      attendance: '/analytics/reports/attendance',
      engagement: '/analytics/reports/engagement',
      performance: '/analytics/reports/performance',
      roi: '/analytics/reports/roi',
    },
  },
  documents: {
    list: '/documents',
    detail: (id: string) => `/documents/${id}`,
    versions: (id: string) => `/documents/${id}/versions`,
    versionDownload: (documentId: string, versionId: string) => `/documents/${documentId}/versions/${versionId}/download`,
    download: (id: string) => `/documents/${id}/download`,
  },
  forum: {
    courseThreads: (courseId: string) => `/forum/courses/${courseId}/threads`,
    thread: (threadId: string) => `/forum/threads/${threadId}`,
    posts: (threadId: string) => `/forum/threads/${threadId}/posts`,
  },
  chat: {
    conversations: '/chat/conversations',
    conversation: (id: string) => `/chat/conversations/${id}`,
    messages: (id: string) => `/chat/conversations/${id}/messages`,
  },
};
