/** Estrutura academica: programas, disciplinas, matrizes, periodos, turmas e matriculas. */
export const academicEndpoints = {
  academic: {
    units: '/academic/units',
    unit: (id: string) => `/academic/units/${id}`,
    programs: '/academic/programs',
    program: (id: string) => `/academic/programs/${id}`,
    programCurricula: (programId: string) => `/academic/programs/${programId}/curricula`,
    subjects: '/academic/subjects',
    subject: (id: string) => `/academic/subjects/${id}`,
    prerequisites: (subjectId: string) => `/academic/subjects/${subjectId}/prerequisites`,
    prerequisite: (subjectId: string, requiredId: string) => `/academic/subjects/${subjectId}/prerequisites/${requiredId}`,
    equivalences: (subjectId: string) => `/academic/subjects/${subjectId}/equivalences`,
    equivalence: (subjectId: string, otherId: string) => `/academic/subjects/${subjectId}/equivalences/${otherId}`,
    curriculum: (id: string) => `/academic/curricula/${id}`,
    curriculumActivate: (id: string) => `/academic/curricula/${id}/activate`,
    curriculumArchive: (id: string) => `/academic/curricula/${id}/archive`,
    curriculumVersions: (id: string) => `/academic/curricula/${id}/versions`,
    curriculumComponents: (id: string) => `/academic/curricula/${id}/components`,
    component: (id: string) => `/academic/curriculum-components/${id}`,
    terms: '/academic/terms',
    term: (id: string) => `/academic/terms/${id}`,
    termStatus: (id: string) => `/academic/terms/${id}/status`,
    termCalendarSummary: (id: string) => `/academic/terms/${id}/calendar-summary`,
    gradingPeriods: (termId: string) => `/academic/terms/${termId}/grading-periods`,
    gradingPeriod: (id: string) => `/academic/grading-periods/${id}`,
    gradingPeriodStatus: (id: string) => `/academic/grading-periods/${id}/status`,
    calendarEvents: '/academic/calendar-events',
    calendarEvent: (id: string) => `/academic/calendar-events/${id}`,
    programEnrollments: '/academic/program-enrollments',
    programEnrollmentStatus: (id: string) => `/academic/program-enrollments/${id}/status`,
    classGroups: '/academic/class-groups',
    classGroup: (id: string) => `/academic/class-groups/${id}`,
    classGroupMembers: (id: string) => `/academic/class-groups/${id}/members`,
    classGroupMember: (id: string, enrollmentId: string) => `/academic/class-groups/${id}/members/${enrollmentId}`,
  },
};
