/** Financeiro: mensalidades, contratos, planos SaaS e cobrancas. */
export const financeEndpoints = {
  tuition: {
    plans: '/tuition/plans',
    plan: (id: string) => `/tuition/plans/${id}`,
    generate: (id: string) => `/tuition/plans/${id}/generate`,
    settings: '/tuition/settings',
    discounts: (enrollmentId: string) => `/tuition/enrollments/${enrollmentId}/discounts`,
    deactivateDiscount: (id: string) => `/tuition/discounts/${id}/deactivate`,
    statement: (enrollmentId: string) => `/tuition/enrollments/${enrollmentId}/charges`,
    myCharges: '/tuition/my/charges',
    quote: (chargeId: string) => `/tuition/charges/${chargeId}/quote`,
    settle: (chargeId: string) => `/tuition/charges/${chargeId}/settle`,
  },
  contracts: {
    templates: '/contracts/templates',
    template: (id: string) => `/contracts/templates/${id}`,
    enrollment: (enrollmentId: string) => `/contracts/enrollments/${enrollmentId}`,
    cancel: (id: string) => `/contracts/${id}/cancel`,
    pdf: (id: string) => `/contracts/${id}/pdf`,
    mine: '/contracts/my',
    myPdf: (id: string) => `/contracts/my/${id}/pdf`,
    accept: (id: string) => `/contracts/my/${id}/accept`,
    validate: (code: string) => `/contracts/validate/${encodeURIComponent(code)}`,
  },
  saas: {
    plans: '/saas/plans',
    plan: (id: string) => `/saas/plans/${id}`,
    institution: (id: string) => `/saas/institutions/${id}`,
    subscription: (id: string) => `/saas/institutions/${id}/subscription`,
    invoices: (id: string) => `/saas/institutions/${id}/invoices`,
    invoicePaid: (id: string) => `/saas/invoices/${id}/paid`,
    current: '/saas/current',
  },
  finance: {
    plans: '/finance/plans',
    plan: (id: string) => `/finance/plans/${id}`,
    subscriptions: '/finance/subscriptions',
    subscription: (id: string) => `/finance/subscriptions/${id}`,
    charges: '/finance/charges',
    charge: (id: string) => `/finance/charges/${id}`,
    chargeAsaas: (id: string) => `/finance/charges/${id}/gateway/asaas`,
    chargePaid: (id: string) => `/finance/charges/${id}/paid`,
    chargeFailed: (id: string) => `/finance/charges/${id}/failed`,
  },
};
