/** Secretaria, matricula por disciplina e integralizacao. */
export const secretariatEndpoints = {
  secretariat: {
    students: '/secretariat/students',
    enrollment: (id: string) => `/secretariat/enrollments/${id}`,
    action: (id: string, action: string) => `/secretariat/enrollments/${id}/${action}`,
    registrations: (id: string) => `/secretariat/enrollments/${id}/registrations`,
    events: (id: string) => `/secretariat/enrollments/${id}/events`,
    creditTransfers: (id: string) => `/secretariat/enrollments/${id}/credit-transfers`,
    creditDecision: (transferId: string) => `/secretariat/credit-transfers/${transferId}/decision`,
    transcript: (id: string) => `/secretariat/enrollments/${id}/transcript`,
    myTranscripts: '/secretariat/my/transcripts',
    declarations: (id: string) => `/secretariat/enrollments/${id}/declarations`,
    declarationPdf: (declarationId: string) => `/secretariat/declarations/${declarationId}/pdf`,
    declarationRevoke: (declarationId: string) => `/secretariat/declarations/${declarationId}/revoke`,
    validateDeclaration: (code: string) => `/secretariat/declarations/validate/${encodeURIComponent(code)}`,
    myDeclarations: '/secretariat/my/declarations',
    myDeclarationPdf: (declarationId: string) => `/secretariat/my/declarations/${declarationId}/pdf`,
    conclusion: (id: string) => `/secretariat/enrollments/${id}/conclusion`,
    ceremony: (id: string) => `/secretariat/enrollments/${id}/ceremony`,
  },
  registration: {
    windows: '/registration/windows',
    window: (id: string) => `/registration/windows/${id}`,
    offeringSlots: (offeringId: string) => `/registration/offerings/${offeringId}/time-slots`,
    slot: (id: string) => `/registration/time-slots/${id}`,
    myWindows: '/registration/my/windows',
    myCatalog: (windowId: string) => `/registration/my/windows/${windowId}/catalog`,
    myOffering: (windowId: string, offeringId: string) => `/registration/my/windows/${windowId}/offerings/${offeringId}`,
    officeCatalog: (enrollmentId: string, termId: string) => `/registration/program-enrollments/${enrollmentId}/terms/${termId}/catalog`,
    officeOffering: (enrollmentId: string, offeringId: string) => `/registration/program-enrollments/${enrollmentId}/offerings/${offeringId}`,
  },
  completion: {
    integralization: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/integralization`,
    myIntegralization: '/completion/my/integralization',
    activities: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/activities`,
    activityDecision: (activityId: string) => `/completion/activities/${activityId}/decision`,
    myActivities: '/completion/my/activities',
    submitActivity: (enrollmentId: string) => `/completion/my/enrollments/${enrollmentId}/activities`,
    myActivity: (activityId: string) => `/completion/my/activities/${activityId}`,
    internships: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/internships`,
    internship: (internshipId: string) => `/completion/internships/${internshipId}`,
    myInternships: '/completion/my/internships',
    internshipLogs: (internshipId: string) => `/completion/internships/${internshipId}/logs`,
    addInternshipLog: (internshipId: string) => `/completion/my/internships/${internshipId}/logs`,
    myInternshipLog: (logId: string) => `/completion/my/internship-logs/${logId}`,
    reviewLog: (logId: string) => `/completion/internship-logs/${logId}/review`,
    finalProject: (enrollmentId: string) => `/completion/enrollments/${enrollmentId}/final-project`,
    finalProjectResult: (projectId: string) => `/completion/final-projects/${projectId}/result`,
    myFinalProjects: '/completion/my/final-projects',
    advising: '/completion/advising',
    advisors: '/completion/advisors',
  },
};
