"""public pages and sales leads

Revision ID: 0002_public_pages
Revises: 0001_initial
Create Date: 2026-10-01 15:53:44.075846

Paginas publicas: dominio proprio da instituicao (escola.com.br) e o conteudo da pagina dela;
interessados em contratar a plataforma, vindos da pagina de contratacao (tabela global, sem RLS).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0002_public_pages'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    # Tipo ja existente (criado com as instituicoes): reaproveitado, nao recriado.
    sa.Column('institution_type', sa.Enum('school', 'university', 'vocational', 'corporate', 'mixed', name='institutiontype').with_variant(postgresql.ENUM(name='institutiontype', create_type=False), 'postgresql'), nullable=False),
    sa.Column('students_estimate', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'proposal', 'won', 'lost', name='leadstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['saas_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_leads_created_at'), 'sales_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_leads_email'), 'sales_leads', ['email'], unique=False)
    op.create_index(op.f('ix_sales_leads_plan_id'), 'sales_leads', ['plan_id'], unique=False)
    op.create_index(op.f('ix_sales_leads_status'), 'sales_leads', ['status'], unique=False)
    op.add_column('institutions', sa.Column('custom_domain', sa.String(length=253), nullable=True))
    op.add_column('institutions', sa.Column('public_profile', sa.JSON(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_institutions_custom_domain'), 'institutions', ['custom_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_custom_domain'), table_name='institutions')
    op.drop_column('institutions', 'public_profile')
    op.drop_column('institutions', 'custom_domain')
    op.drop_index(op.f('ix_sales_leads_status'), table_name='sales_leads')
    op.drop_index(op.f('ix_sales_leads_plan_id'), table_name='sales_leads')
    op.drop_index(op.f('ix_sales_leads_email'), table_name='sales_leads')
    op.drop_index(op.f('ix_sales_leads_created_at'), table_name='sales_leads')
    op.drop_table('sales_leads')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TYPE IF EXISTS leadstatus')
