"""benefit vouchers

Revision ID: 0004_benefit_vouchers
Revises: 0003_data_versions
Create Date: 2026-10-01 19:30:44.472622

Beneficio liberado ao aluno para retirada com QR (cantina, kits): reserva o estoque ate a validacao,
que gera a entrega. Tabela de instituicao, com RLS.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_benefit_vouchers'
down_revision: Union[str, Sequence[str], None] = '0003_data_versions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::uuid"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_vouchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_offering_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_meeting_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('released', 'redeemed', 'cancelled', name='voucherstatus'), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('released_by_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_by_id', sa.Uuid(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['benefit_deliveries.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['benefit_items.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheduled_meeting_id'], ['scheduled_meetings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_vouchers_class_offering_id'), 'benefit_vouchers', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_benefit_vouchers_code'), 'benefit_vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_benefit_vouchers_institution_id'), 'benefit_vouchers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_benefit_vouchers_item_id'), 'benefit_vouchers', ['item_id'], unique=False)
    op.create_index(op.f('ix_benefit_vouchers_scheduled_meeting_id'), 'benefit_vouchers', ['scheduled_meeting_id'], unique=False)
    op.create_index(op.f('ix_benefit_vouchers_status'), 'benefit_vouchers', ['status'], unique=False)
    op.create_index(op.f('ix_benefit_vouchers_student_id'), 'benefit_vouchers', ['student_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE benefit_vouchers ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE benefit_vouchers FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY {POLICY} ON benefit_vouchers USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefit_vouchers_student_id'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_status'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_scheduled_meeting_id'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_item_id'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_institution_id'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_code'), table_name='benefit_vouchers')
    op.drop_index(op.f('ix_benefit_vouchers_class_offering_id'), table_name='benefit_vouchers')
    op.drop_table('benefit_vouchers')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TYPE IF EXISTS voucherstatus')
