"""warehouse pickup control

Revision ID: 0005_warehouse_pickup
Revises: 0004_benefit_vouchers
Create Date: 2026-10-01 19:58:56.203328

Almoxarifado: QR de retirada (codigo gerado na aprovacao), forma da retirada (QR ou manual com
justificativa) e devolucoes como eventos (quem recebeu, quando), base do historico por material.
Requisicoes ja aprovadas recebem codigo. Tabela de devolucoes e de instituicao, com RLS.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_warehouse_pickup'
down_revision: Union[str, Sequence[str], None] = '0004_benefit_vouchers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::uuid"
DELIVERY_METHOD = sa.Enum('qr', 'manual', name='deliverymethod')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_returns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('returned', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['warehouse_items.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['material_request_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_returns_institution_id'), 'material_returns', ['institution_id'], unique=False)
    op.create_index(op.f('ix_material_returns_item_id'), 'material_returns', ['item_id'], unique=False)
    op.create_index(op.f('ix_material_returns_line_id'), 'material_returns', ['line_id'], unique=False)
    op.create_index(op.f('ix_material_returns_request_id'), 'material_returns', ['request_id'], unique=False)
    op.add_column('material_requests', sa.Column('pickup_code', sa.String(length=40), nullable=True))
    DELIVERY_METHOD.create(op.get_bind(), checkfirst=True)
    op.add_column('material_requests', sa.Column('delivery_method', DELIVERY_METHOD, nullable=True))
    op.add_column('material_requests', sa.Column('delivery_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_material_requests_pickup_code'), 'material_requests', ['pickup_code'], unique=True)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE material_returns ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE material_returns FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY {POLICY} ON material_returns USING ({CONDITION}) WITH CHECK ({CONDITION})")
        # Aprovadas antes desta versao tambem ganham QR de retirada.
        op.execute("UPDATE material_requests SET pickup_code = md5(random()::text || id::text) WHERE status = 'approved'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_requests_pickup_code'), table_name='material_requests')
    op.drop_column('material_requests', 'delivery_note')
    op.drop_column('material_requests', 'delivery_method')
    op.drop_column('material_requests', 'pickup_code')
    op.drop_index(op.f('ix_material_returns_request_id'), table_name='material_returns')
    op.drop_index(op.f('ix_material_returns_line_id'), table_name='material_returns')
    op.drop_index(op.f('ix_material_returns_item_id'), table_name='material_returns')
    op.drop_index(op.f('ix_material_returns_institution_id'), table_name='material_returns')
    op.drop_table('material_returns')
    # ### end Alembic commands ###
    DELIVERY_METHOD.drop(op.get_bind(), checkfirst=True)
