"""facial identity

Identidade facial (Persona): data de nascimento do usuario, que decide a maioridade exigida
pela presenca facial, e os assertions de login facial ja usados (uso unico do `jti`). A tabela
de assertions e da plataforma, sem instituicao (como `users`), sem RLS.

Revision ID: 0006_facial_identity
Revises: 0005_warehouse_pickup
Create Date: 2026-10-03 23:28:15.557055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_facial_identity'
down_revision: Union[str, Sequence[str], None] = '0005_warehouse_pickup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facial_login_assertions',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_facial_login_assertions_user_id'), 'facial_login_assertions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.drop_index(op.f('ix_facial_login_assertions_user_id'), table_name='facial_login_assertions')
    op.drop_table('facial_login_assertions')
    # ### end Alembic commands ###
