"""persona integration

Revision ID: 0007_persona_integration
Revises: 0006_facial_identity
Create Date: 2026-10-04 11:11:04.137651

Integracao com o Persona: passagens pela catraca avisadas por ele (gate_passages, de instituicao,
com RLS; jti unico contra reenvio) e o tipo de aviso gate_passage; fins de vinculo
(membership_events, da plataforma como institution_memberships) para o Persona revogar o acesso.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_persona_integration'
down_revision: Union[str, Sequence[str], None] = '0006_facial_identity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::uuid"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_events_created_at'), 'membership_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_membership_events_institution_id'), 'membership_events', ['institution_id'], unique=False)
    op.create_index(op.f('ix_membership_events_user_id'), 'membership_events', ['user_id'], unique=False)
    op.create_table('gate_passages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_passages_institution_id'), 'gate_passages', ['institution_id'], unique=False)
    op.create_index(op.f('ix_gate_passages_jti'), 'gate_passages', ['jti'], unique=True)
    op.create_index(op.f('ix_gate_passages_occurred_at'), 'gate_passages', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_gate_passages_student_id'), 'gate_passages', ['student_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'gate_passage'")
        op.execute("ALTER TABLE gate_passages ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE gate_passages FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY {POLICY} ON gate_passages USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_passages_student_id'), table_name='gate_passages')
    op.drop_index(op.f('ix_gate_passages_occurred_at'), table_name='gate_passages')
    op.drop_index(op.f('ix_gate_passages_jti'), table_name='gate_passages')
    op.drop_index(op.f('ix_gate_passages_institution_id'), table_name='gate_passages')
    op.drop_table('gate_passages')
    op.drop_index(op.f('ix_membership_events_user_id'), table_name='membership_events')
    op.drop_index(op.f('ix_membership_events_institution_id'), table_name='membership_events')
    op.drop_index(op.f('ix_membership_events_created_at'), table_name='membership_events')
    op.drop_table('membership_events')
    # ### end Alembic commands ###
    # O valor 'gate_passage' fica no tipo notificationeventtype (PostgreSQL nao remove valor de enum).
