"""add subject registration windows and time slots

Revision ID: a2b3c4d5e6f2
Revises: f1a2b3c4d5e1
Create Date: 2026-10-01 01:23:06.597695

Fase 16 (entrega 1): janelas de matricula por disciplina e horario semanal das
ofertas (choque de horario). Novas tabelas recebem a politica
`tenant_isolation`; novo evento `waitlist_promoted`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b3c4d5e6f2'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["registration_windows", "offering_time_slots"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'waitlist_promoted'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_credits', sa.Integer(), nullable=True),
    sa.Column('max_credits', sa.Integer(), nullable=True),
    sa.Column('allow_waitlist', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_windows_institution_id'), 'registration_windows', ['institution_id'], unique=False)
    op.create_index(op.f('ix_registration_windows_program_id'), 'registration_windows', ['program_id'], unique=False)
    op.create_index(op.f('ix_registration_windows_term_id'), 'registration_windows', ['term_id'], unique=False)
    op.create_table('offering_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offering_time_slots_class_offering_id'), 'offering_time_slots', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_offering_time_slots_institution_id'), 'offering_time_slots', ['institution_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offering_time_slots_institution_id'), table_name='offering_time_slots')
    op.drop_index(op.f('ix_offering_time_slots_class_offering_id'), table_name='offering_time_slots')
    op.drop_table('offering_time_slots')
    op.drop_index(op.f('ix_registration_windows_term_id'), table_name='registration_windows')
    op.drop_index(op.f('ix_registration_windows_program_id'), table_name='registration_windows')
    op.drop_index(op.f('ix_registration_windows_institution_id'), table_name='registration_windows')
    op.drop_table('registration_windows')
    # ### end Alembic commands ###
