"""add minimum wage values

Revision ID: a8b9c0d1e2f8
Revises: f7a8b9c0d1e7
Create Date: 2026-10-01 08:28:31.383444

Fase 18: tabela local do salario minimo (serie 1619 do SGS do Banco
Central), ja carregada com os valores desde 2000 para funcionar sem a API.
Tabela global, sem instituicao.

"""
from typing import Sequence, Union

from datetime import date, datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b9c0d1e2f8'
down_revision: Union[str, Sequence[str], None] = 'f7a8b9c0d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mudancas de valor da serie 1619 do SGS (consultadas em 2026-10-01); maio/1999 cobre o inicio de 2000.
KNOWN_VALUES = [
    (date(1999, 5, 1), 13600),
    (date(2000, 4, 1), 15100),
    (date(2001, 4, 1), 18000),
    (date(2002, 4, 1), 20000),
    (date(2003, 4, 1), 24000),
    (date(2004, 5, 1), 26000),
    (date(2005, 5, 1), 30000),
    (date(2006, 4, 1), 35000),
    (date(2007, 4, 1), 38000),
    (date(2008, 3, 1), 41500),
    (date(2009, 2, 1), 46500),
    (date(2010, 1, 1), 51000),
    (date(2011, 1, 1), 54000),
    (date(2011, 3, 1), 54500),
    (date(2012, 1, 1), 62200),
    (date(2013, 1, 1), 67800),
    (date(2014, 1, 1), 72400),
    (date(2015, 1, 1), 78800),
    (date(2016, 1, 1), 88000),
    (date(2017, 1, 1), 93700),
    (date(2018, 1, 1), 95400),
    (date(2019, 1, 1), 99800),
    (date(2020, 1, 1), 103900),
    (date(2020, 2, 1), 104500),
    (date(2021, 1, 1), 110000),
    (date(2022, 1, 1), 121200),
    (date(2023, 1, 1), 130200),
    (date(2023, 5, 1), 132000),
    (date(2024, 1, 1), 141200),
    (date(2025, 1, 1), 151800),
    (date(2026, 1, 1), 162100),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('minimum_wage_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('cents', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minimum_wage_values_valid_from'), 'minimum_wage_values', ['valid_from'], unique=True)
    # ### end Alembic commands ###

    synced_at = datetime(2026, 10, 1, tzinfo=timezone.utc)
    op.bulk_insert(table, [
        {"valid_from": valid_from, "cents": cents, "source": "seed", "synced_at": synced_at} for valid_from, cents in KNOWN_VALUES
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_minimum_wage_values_valid_from'), table_name='minimum_wage_values')
    op.drop_table('minimum_wage_values')
    # ### end Alembic commands ###
