"""add completion requirements

Revision ID: b3c4d5e6f7a3
Revises: a2b3c4d5e6f2
Create Date: 2026-10-01 01:35:10.361959

Fase 16 (entrega 2): requisitos de conclusao alem das disciplinas
(atividades complementares, estagio com diario de horas e TCC) e metas do
programa. Novas tabelas recebem a politica `tenant_isolation`; novo evento
`activity_reviewed`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c4d5e6f7a3'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["complementary_activities", "final_projects", "internships", "internship_logs"]
ENUMS = ["activitycategory", "reviewstatus", "internshipstatus", "finalprojectstatus"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'activity_reviewed'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complementary_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('teaching', 'research', 'extension', 'cultural', 'professional', 'other', name='activitycategory'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('hours_requested', sa.Integer(), nullable=False),
    sa.Column('hours_approved', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complementary_activities_institution_id'), 'complementary_activities', ['institution_id'], unique=False)
    op.create_index(op.f('ix_complementary_activities_program_enrollment_id'), 'complementary_activities', ['program_enrollment_id'], unique=False)
    op.create_table('final_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('co_advisor_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'approved', 'failed', name='finalprojectstatus'), nullable=False),
    sa.Column('defense_on', sa.Date(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('committee', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_projects_advisor_id'), 'final_projects', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_final_projects_institution_id'), 'final_projects', ['institution_id'], unique=False)
    op.create_index(op.f('ix_final_projects_program_enrollment_id'), 'final_projects', ['program_enrollment_id'], unique=True)
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('supervisor_name', sa.String(length=200), nullable=True),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('agreement_number', sa.String(length=80), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('planned_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'cancelled', name='internshipstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_advisor_id'), 'internships', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_internships_institution_id'), 'internships', ['institution_id'], unique=False)
    op.create_index(op.f('ix_internships_program_enrollment_id'), 'internships', ['program_enrollment_id'], unique=False)
    op.create_table('internship_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('worked_on', sa.Date(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('activities', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internship_logs_institution_id'), 'internship_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_internship_logs_internship_id'), 'internship_logs', ['internship_id'], unique=False)
    op.add_column('programs', sa.Column('complementary_hours', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('internship_hours', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('requires_final_project', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'requires_final_project')
    op.drop_column('programs', 'internship_hours')
    op.drop_column('programs', 'complementary_hours')
    op.drop_index(op.f('ix_internship_logs_internship_id'), table_name='internship_logs')
    op.drop_index(op.f('ix_internship_logs_institution_id'), table_name='internship_logs')
    op.drop_table('internship_logs')
    op.drop_index(op.f('ix_internships_program_enrollment_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_institution_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_advisor_id'), table_name='internships')
    op.drop_table('internships')
    op.drop_index(op.f('ix_final_projects_program_enrollment_id'), table_name='final_projects')
    op.drop_index(op.f('ix_final_projects_institution_id'), table_name='final_projects')
    op.drop_index(op.f('ix_final_projects_advisor_id'), table_name='final_projects')
    op.drop_table('final_projects')
    op.drop_index(op.f('ix_complementary_activities_program_enrollment_id'), table_name='complementary_activities')
    op.drop_index(op.f('ix_complementary_activities_institution_id'), table_name='complementary_activities')
    op.drop_table('complementary_activities')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
