"""add secretariat

Revision ID: b7c8d9e0f1ad
Revises: a6b7c8d9e0fc
Create Date: 2026-09-30 23:06:04.404331

Fase 14 (entrega 1): movimentacoes da matricula, rematricula por periodo,
aproveitamento de estudos e vinculo de transferencia interna.
Novas tabelas recebem a politica `tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c8d9e0f1ad'
down_revision: Union[str, Sequence[str], None] = 'a6b7c8d9e0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["program_enrollment_events", "term_registrations", "credit_transfers"]
ENUMS = ["enrollmenteventkind", "credittransferorigin", "credittransferstatus"]
TRANSFER_FK = "fk_program_enrollments_transferred_from_id"


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('internal', 'external', name='credittransferorigin'), nullable=False),
    sa.Column('source_institution', sa.String(length=200), nullable=True),
    sa.Column('source_subject', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', name='credittransferstatus'), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transfers_institution_id'), 'credit_transfers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_credit_transfers_program_enrollment_id'), 'credit_transfers', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_credit_transfers_subject_id'), 'credit_transfers', ['subject_id'], unique=False)
    op.create_table('program_enrollment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('enrolled', 'reenrolled', 'locked', 'reactivated', 'cancelled', 'dropped', 'transferred_out', 'transferred_internal', 'curriculum_changed', 'graduated', name='enrollmenteventkind'), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_enrollment_events_institution_id'), 'program_enrollment_events', ['institution_id'], unique=False)
    op.create_index(op.f('ix_program_enrollment_events_program_enrollment_id'), 'program_enrollment_events', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_program_enrollment_events_term_id'), 'program_enrollment_events', ['term_id'], unique=False)
    op.create_table('term_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_term_number', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_enrollment_id', 'term_id')
    )
    op.create_index(op.f('ix_term_registrations_institution_id'), 'term_registrations', ['institution_id'], unique=False)
    op.create_index(op.f('ix_term_registrations_program_enrollment_id'), 'term_registrations', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_term_registrations_term_id'), 'term_registrations', ['term_id'], unique=False)
    op.add_column('program_enrollments', sa.Column('transferred_from_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_program_enrollments_transferred_from_id'), 'program_enrollments', ['transferred_from_id'], unique=False)
    op.create_foreign_key(TRANSFER_FK, 'program_enrollments', 'program_enrollments', ['transferred_from_id'], ['id'])
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(TRANSFER_FK, 'program_enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_program_enrollments_transferred_from_id'), table_name='program_enrollments')
    op.drop_column('program_enrollments', 'transferred_from_id')
    op.drop_index(op.f('ix_term_registrations_term_id'), table_name='term_registrations')
    op.drop_index(op.f('ix_term_registrations_program_enrollment_id'), table_name='term_registrations')
    op.drop_index(op.f('ix_term_registrations_institution_id'), table_name='term_registrations')
    op.drop_table('term_registrations')
    op.drop_index(op.f('ix_program_enrollment_events_term_id'), table_name='program_enrollment_events')
    op.drop_index(op.f('ix_program_enrollment_events_program_enrollment_id'), table_name='program_enrollment_events')
    op.drop_index(op.f('ix_program_enrollment_events_institution_id'), table_name='program_enrollment_events')
    op.drop_table('program_enrollment_events')
    op.drop_index(op.f('ix_credit_transfers_subject_id'), table_name='credit_transfers')
    op.drop_index(op.f('ix_credit_transfers_program_enrollment_id'), table_name='credit_transfers')
    op.drop_index(op.f('ix_credit_transfers_institution_id'), table_name='credit_transfers')
    op.drop_table('credit_transfers')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum_name in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
