"""add access roles

Revision ID: b9c0d1e2f3a9
Revises: a8b9c0d1e2f8
Create Date: 2026-10-01 08:35:34.491143

RBAC: perfis de acesso da instituicao (conjunto de permissoes do catalogo)
e atribuicoes a usuarios. Os papeis existentes viram perfis padrao no
codigo, sem dados a migrar. Novas tabelas recebem a politica
`tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c0d1e2f3a9'
down_revision: Union[str, Sequence[str], None] = 'a8b9c0d1e2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["access_roles", "access_role_assignments"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name')
    )
    op.create_index(op.f('ix_access_roles_institution_id'), 'access_roles', ['institution_id'], unique=False)
    op.create_table('access_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['access_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'user_id')
    )
    op.create_index(op.f('ix_access_role_assignments_institution_id'), 'access_role_assignments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_access_role_assignments_role_id'), 'access_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_access_role_assignments_user_id'), 'access_role_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_role_assignments_user_id'), table_name='access_role_assignments')
    op.drop_index(op.f('ix_access_role_assignments_role_id'), table_name='access_role_assignments')
    op.drop_index(op.f('ix_access_role_assignments_institution_id'), table_name='access_role_assignments')
    op.drop_table('access_role_assignments')
    op.drop_index(op.f('ix_access_roles_institution_id'), table_name='access_roles')
    op.drop_table('access_roles')
    # ### end Alembic commands ###
