"""add warehouse

Revision ID: c0d1e2f3a4b0
Revises: b9c0d1e2f3a9
Create Date: 2026-10-01 08:43:06.053504

Almoxarifado: materiais (consumo ou permanentes), entradas, requisicoes
com aprovacao, retirada e devolucao. Novas tabelas recebem a politica
`tenant_isolation`; novo evento `material_request_decided`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d1e2f3a4b0'
down_revision: Union[str, Sequence[str], None] = 'b9c0d1e2f3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["warehouse_items", "warehouse_entries", "material_requests", "material_request_lines"]
ENUMS = ["materialkind", "entryorigin", "requeststatus"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'material_request_decided'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.Enum('consumable', 'durable', name='materialkind'), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_items_institution_id'), 'warehouse_items', ['institution_id'], unique=False)
    op.create_table('warehouse_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('purchase', 'donation', name='entryorigin'), nullable=False),
    sa.Column('funding_source_id', sa.Integer(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_sources.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['warehouse_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_entries_funding_source_id'), 'warehouse_entries', ['funding_source_id'], unique=False)
    op.create_index(op.f('ix_warehouse_entries_institution_id'), 'warehouse_entries', ['institution_id'], unique=False)
    op.create_index(op.f('ix_warehouse_entries_item_id'), 'warehouse_entries', ['item_id'], unique=False)
    op.create_table('material_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('needed_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'delivered', 'closed', 'cancelled', name='requeststatus'), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_due_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_class_offering_id'), 'material_requests', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_material_requests_institution_id'), 'material_requests', ['institution_id'], unique=False)
    op.create_index(op.f('ix_material_requests_requester_id'), 'material_requests', ['requester_id'], unique=False)
    op.create_table('material_request_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=True),
    sa.Column('quantity_delivered', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('quantity_lost', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['warehouse_items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_request_lines_institution_id'), 'material_request_lines', ['institution_id'], unique=False)
    op.create_index(op.f('ix_material_request_lines_item_id'), 'material_request_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_material_request_lines_request_id'), 'material_request_lines', ['request_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_request_lines_request_id'), table_name='material_request_lines')
    op.drop_index(op.f('ix_material_request_lines_item_id'), table_name='material_request_lines')
    op.drop_index(op.f('ix_material_request_lines_institution_id'), table_name='material_request_lines')
    op.drop_table('material_request_lines')
    op.drop_index(op.f('ix_material_requests_requester_id'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_institution_id'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_class_offering_id'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_warehouse_entries_item_id'), table_name='warehouse_entries')
    op.drop_index(op.f('ix_warehouse_entries_institution_id'), table_name='warehouse_entries')
    op.drop_index(op.f('ix_warehouse_entries_funding_source_id'), table_name='warehouse_entries')
    op.drop_table('warehouse_entries')
    op.drop_index(op.f('ix_warehouse_items_institution_id'), table_name='warehouse_items')
    op.drop_table('warehouse_items')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
