"""add tuition plans and discounts

Revision ID: c4d5e6f7a8b4
Revises: b3c4d5e6f7a3
Create Date: 2026-10-01 01:47:43.354391

Fase 17 (entrega 1): planos de mensalidade (programa, turma-grupo ou
credito), bolsas e descontos da matricula e composicao da cobranca
(parcela, pagador, descontos, multa, juros e valor pago). Novas tabelas
recebem a politica `tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d5e6f7a8b4'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["tuition_plans", "student_discounts"]
ENUMS = ["tuitionbasis", "discountkind"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('basis', sa.Enum('program', 'class_group', 'credit', name='tuitionbasis'), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('first_due_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuition_plans_class_group_id'), 'tuition_plans', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_tuition_plans_institution_id'), 'tuition_plans', ['institution_id'], unique=False)
    op.create_index(op.f('ix_tuition_plans_program_id'), 'tuition_plans', ['program_id'], unique=False)
    op.create_index(op.f('ix_tuition_plans_term_id'), 'tuition_plans', ['term_id'], unique=False)
    op.create_table('student_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('scholarship', 'sibling', 'punctuality', 'agreement', 'other', name='discountkind'), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_discounts_institution_id'), 'student_discounts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_discounts_program_enrollment_id'), 'student_discounts', ['program_enrollment_id'], unique=False)
    op.add_column('charges', sa.Column('program_enrollment_id', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('tuition_plan_id', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('payer_id', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('gross_amount_cents', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('discount_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('charges', sa.Column('punctuality_discount_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('charges', sa.Column('fine_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('charges', sa.Column('interest_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('charges', sa.Column('amount_paid_cents', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_charges_payer_id'), 'charges', ['payer_id'], unique=False)
    op.create_index(op.f('ix_charges_program_enrollment_id'), 'charges', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_charges_tuition_plan_id'), 'charges', ['tuition_plan_id'], unique=False)
    op.create_unique_constraint('uq_charges_tuition_installment', 'charges', ['program_enrollment_id', 'tuition_plan_id', 'installment_number'])
    op.create_foreign_key('fk_charges_program_enrollment_id', 'charges', 'program_enrollments', ['program_enrollment_id'], ['id'])
    op.create_foreign_key('fk_charges_tuition_plan_id', 'charges', 'tuition_plans', ['tuition_plan_id'], ['id'])
    op.create_foreign_key('fk_charges_payer_id', 'charges', 'users', ['payer_id'], ['id'])
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_charges_payer_id', 'charges', type_='foreignkey')
    op.drop_constraint('fk_charges_tuition_plan_id', 'charges', type_='foreignkey')
    op.drop_constraint('fk_charges_program_enrollment_id', 'charges', type_='foreignkey')
    op.drop_constraint('uq_charges_tuition_installment', 'charges', type_='unique')
    op.drop_index(op.f('ix_charges_tuition_plan_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_program_enrollment_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_payer_id'), table_name='charges')
    op.drop_column('charges', 'amount_paid_cents')
    op.drop_column('charges', 'interest_cents')
    op.drop_column('charges', 'fine_cents')
    op.drop_column('charges', 'punctuality_discount_cents')
    op.drop_column('charges', 'discount_cents')
    op.drop_column('charges', 'gross_amount_cents')
    op.drop_column('charges', 'payer_id')
    op.drop_column('charges', 'installment_number')
    op.drop_column('charges', 'tuition_plan_id')
    op.drop_column('charges', 'program_enrollment_id')
    op.drop_index(op.f('ix_student_discounts_program_enrollment_id'), table_name='student_discounts')
    op.drop_index(op.f('ix_student_discounts_institution_id'), table_name='student_discounts')
    op.drop_table('student_discounts')
    op.drop_index(op.f('ix_tuition_plans_term_id'), table_name='tuition_plans')
    op.drop_index(op.f('ix_tuition_plans_program_id'), table_name='tuition_plans')
    op.drop_index(op.f('ix_tuition_plans_institution_id'), table_name='tuition_plans')
    op.drop_index(op.f('ix_tuition_plans_class_group_id'), table_name='tuition_plans')
    op.drop_table('tuition_plans')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
