"""add declarations and program conclusion

Revision ID: c8d9e0f1a2be
Revises: b7c8d9e0f1ad
Create Date: 2026-09-30 23:23:20.883434

Fase 14 (entrega 2): declaracoes assinadas com validacao publica e datas de
conclusao e colacao na matricula do programa. A nova tabela recebe a politica
`tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d9e0f1a2be'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('enrollment', 'attendance', 'completion', name='declarationkind'), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('validation_code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_hash', sa.String(length=128), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_declarations_institution_id'), 'academic_declarations', ['institution_id'], unique=False)
    op.create_index(op.f('ix_academic_declarations_program_enrollment_id'), 'academic_declarations', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_academic_declarations_validation_code'), 'academic_declarations', ['validation_code'], unique=True)
    op.add_column('program_enrollments', sa.Column('concluded_on', sa.Date(), nullable=True))
    op.add_column('program_enrollments', sa.Column('ceremony_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    if _is_postgres():
        op.execute("ALTER TABLE academic_declarations ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE academic_declarations FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY {POLICY} ON academic_declarations USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_enrollments', 'ceremony_on')
    op.drop_column('program_enrollments', 'concluded_on')
    op.drop_index(op.f('ix_academic_declarations_validation_code'), table_name='academic_declarations')
    op.drop_index(op.f('ix_academic_declarations_program_enrollment_id'), table_name='academic_declarations')
    op.drop_index(op.f('ix_academic_declarations_institution_id'), table_name='academic_declarations')
    op.drop_table('academic_declarations')
    # ### end Alembic commands ###

    if _is_postgres():
        op.execute("DROP TYPE IF EXISTS declarationkind")
