"""add curricular structure

Revision ID: d3e4f5a6b7c9
Revises: c2d3e4f5a6b8
Create Date: 2026-09-30 21:55:10.851838

Fase 12 (entrega 1): unidades academicas, programas, disciplinas com
pre-requisitos/equivalencias e matriz curricular versionada. Todas as tabelas
recebem a politica `tenant_isolation` (mesma condicao de c2d3e4f5a6b8 e
app/core/tenant_rls.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e4f5a6b7c9'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = [
    "academic_units",
    "programs",
    "subjects",
    "subject_prerequisites",
    "subject_equivalences",
    "curricula",
    "curriculum_components",
]
ENUMS = ["academicunitkind", "programlevel", "programstatus", "curriculumstatus", "componentkind"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('segment', 'faculty', 'department', 'axis', 'other', name='academicunitkind'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['academic_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_units_institution_id'), 'academic_units', ['institution_id'], unique=False)
    op.create_index(op.f('ix_academic_units_parent_id'), 'academic_units', ['parent_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('basic', 'technical', 'undergraduate', 'graduate', 'free', name='programlevel'), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=True),
    sa.Column('duration_terms', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', name='programstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['academic_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code')
    )
    op.create_index(op.f('ix_programs_institution_id'), 'programs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_programs_unit_id'), 'programs', ['unit_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code')
    )
    op.create_index(op.f('ix_subjects_course_id'), 'subjects', ['course_id'], unique=False)
    op.create_index(op.f('ix_subjects_institution_id'), 'subjects', ['institution_id'], unique=False)
    op.create_table('curricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='curriculumstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'version')
    )
    op.create_index(op.f('ix_curricula_institution_id'), 'curricula', ['institution_id'], unique=False)
    op.create_index(op.f('ix_curricula_program_id'), 'curricula', ['program_id'], unique=False)
    op.create_table('subject_equivalences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('equivalent_subject_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equivalent_subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'equivalent_subject_id')
    )
    op.create_index(op.f('ix_subject_equivalences_equivalent_subject_id'), 'subject_equivalences', ['equivalent_subject_id'], unique=False)
    op.create_index(op.f('ix_subject_equivalences_institution_id'), 'subject_equivalences', ['institution_id'], unique=False)
    op.create_index(op.f('ix_subject_equivalences_subject_id'), 'subject_equivalences', ['subject_id'], unique=False)
    op.create_table('subject_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('required_subject_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['required_subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'required_subject_id')
    )
    op.create_index(op.f('ix_subject_prerequisites_institution_id'), 'subject_prerequisites', ['institution_id'], unique=False)
    op.create_index(op.f('ix_subject_prerequisites_required_subject_id'), 'subject_prerequisites', ['required_subject_id'], unique=False)
    op.create_index(op.f('ix_subject_prerequisites_subject_id'), 'subject_prerequisites', ['subject_id'], unique=False)
    op.create_table('curriculum_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('mandatory', 'elective', 'optional', name='componentkind'), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'subject_id')
    )
    op.create_index(op.f('ix_curriculum_components_curriculum_id'), 'curriculum_components', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_curriculum_components_institution_id'), 'curriculum_components', ['institution_id'], unique=False)
    op.create_index(op.f('ix_curriculum_components_subject_id'), 'curriculum_components', ['subject_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_components_subject_id'), table_name='curriculum_components')
    op.drop_index(op.f('ix_curriculum_components_institution_id'), table_name='curriculum_components')
    op.drop_index(op.f('ix_curriculum_components_curriculum_id'), table_name='curriculum_components')
    op.drop_table('curriculum_components')
    op.drop_index(op.f('ix_subject_prerequisites_subject_id'), table_name='subject_prerequisites')
    op.drop_index(op.f('ix_subject_prerequisites_required_subject_id'), table_name='subject_prerequisites')
    op.drop_index(op.f('ix_subject_prerequisites_institution_id'), table_name='subject_prerequisites')
    op.drop_table('subject_prerequisites')
    op.drop_index(op.f('ix_subject_equivalences_subject_id'), table_name='subject_equivalences')
    op.drop_index(op.f('ix_subject_equivalences_institution_id'), table_name='subject_equivalences')
    op.drop_index(op.f('ix_subject_equivalences_equivalent_subject_id'), table_name='subject_equivalences')
    op.drop_table('subject_equivalences')
    op.drop_index(op.f('ix_curricula_program_id'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_institution_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_subjects_institution_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_course_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_programs_unit_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_institution_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_academic_units_parent_id'), table_name='academic_units')
    op.drop_index(op.f('ix_academic_units_institution_id'), table_name='academic_units')
    op.drop_table('academic_units')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum_name in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
