"""add contracts and saas plans

Revision ID: d5e6f7a8b9c5
Revises: c4d5e6f7a8b4
Create Date: 2026-10-01 01:58:54.208761

Fase 17 (entrega 2): modelos e contratos de matricula/rematricula (texto
congelado, documento no GED, aceite com assinatura de integridade) e
planos SaaS da plataforma (assinatura e faturas por instituicao; tabelas
globais, sem tenant). As tabelas de contrato recebem a politica
`tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e6f7a8b9c5'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["contract_templates", "enrollment_contracts"]
ENUMS = ["contractkind", "contractstatus", "saassubscriptionstatus", "platforminvoicestatus"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saas_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('enrollment', 'reenrollment', name='contractkind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_institution_id'), 'contract_templates', ['institution_id'], unique=False)
    op.create_table('institution_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'past_due', 'cancelled', name='saassubscriptionstatus'), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('trial_ends_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['saas_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_subscriptions_institution_id'), 'institution_subscriptions', ['institution_id'], unique=True)
    op.create_index(op.f('ix_institution_subscriptions_plan_id'), 'institution_subscriptions', ['plan_id'], unique=False)
    op.create_table('platform_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', name='platforminvoicestatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['institution_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'period_start')
    )
    op.create_index(op.f('ix_platform_invoices_institution_id'), 'platform_invoices', ['institution_id'], unique=False)
    op.create_index(op.f('ix_platform_invoices_subscription_id'), 'platform_invoices', ['subscription_id'], unique=False)
    op.create_table('enrollment_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('enrollment', 'reenrollment', name='contractkind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'signed', 'cancelled', name='contractstatus'), nullable=False),
    sa.Column('validation_code', sa.String(length=40), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_hash', sa.String(length=128), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_contracts_document_id'), 'enrollment_contracts', ['document_id'], unique=False)
    op.create_index(op.f('ix_enrollment_contracts_institution_id'), 'enrollment_contracts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_enrollment_contracts_program_enrollment_id'), 'enrollment_contracts', ['program_enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollment_contracts_template_id'), 'enrollment_contracts', ['template_id'], unique=False)
    op.create_index(op.f('ix_enrollment_contracts_term_id'), 'enrollment_contracts', ['term_id'], unique=False)
    op.create_index(op.f('ix_enrollment_contracts_validation_code'), 'enrollment_contracts', ['validation_code'], unique=True)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_contracts_validation_code'), table_name='enrollment_contracts')
    op.drop_index(op.f('ix_enrollment_contracts_term_id'), table_name='enrollment_contracts')
    op.drop_index(op.f('ix_enrollment_contracts_template_id'), table_name='enrollment_contracts')
    op.drop_index(op.f('ix_enrollment_contracts_program_enrollment_id'), table_name='enrollment_contracts')
    op.drop_index(op.f('ix_enrollment_contracts_institution_id'), table_name='enrollment_contracts')
    op.drop_index(op.f('ix_enrollment_contracts_document_id'), table_name='enrollment_contracts')
    op.drop_table('enrollment_contracts')
    op.drop_index(op.f('ix_platform_invoices_subscription_id'), table_name='platform_invoices')
    op.drop_index(op.f('ix_platform_invoices_institution_id'), table_name='platform_invoices')
    op.drop_table('platform_invoices')
    op.drop_index(op.f('ix_institution_subscriptions_plan_id'), table_name='institution_subscriptions')
    op.drop_index(op.f('ix_institution_subscriptions_institution_id'), table_name='institution_subscriptions')
    op.drop_table('institution_subscriptions')
    op.drop_index(op.f('ix_contract_templates_institution_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_table('saas_plans')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
