"""add student guardians

Revision ID: d9e0f1a2b3cf
Revises: c8d9e0f1a2be
Create Date: 2026-09-30 23:35:07.425617

Fase 15 (entrega 1): vinculo aluno-responsavel (parentesco, responsavel
financeiro, autorizacao de retirada). A nova tabela recebe a politica
`tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e0f1a2b3cf'
down_revision: Union[str, Sequence[str], None] = 'c8d9e0f1a2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('relationship_kind', sa.Enum('mother', 'father', 'legal_guardian', 'grandparent', 'other', name='guardianrelationship'), nullable=False),
    sa.Column('is_financial', sa.Boolean(), nullable=False),
    sa.Column('can_pick_up', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'guardian_id')
    )
    op.create_index(op.f('ix_student_guardians_guardian_id'), 'student_guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_institution_id'), 'student_guardians', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        op.execute("ALTER TABLE student_guardians ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE student_guardians FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY {POLICY} ON student_guardians USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_institution_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_guardian_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    # ### end Alembic commands ###

    if _is_postgres():
        op.execute("DROP TYPE IF EXISTS guardianrelationship")
