"""add occurrences and school agenda

Revision ID: e0f1a2b3c4d0
Revises: d9e0f1a2b3cf
Create Date: 2026-09-30 23:48:33.589273

Fase 15 (entrega 2): ocorrencias disciplinares/pedagogicas do aluno e agenda
da turma, com eventos de notificacao para os responsaveis. Novas tabelas
recebem a politica `tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f1a2b3c4d0'
down_revision: Union[str, Sequence[str], None] = 'd9e0f1a2b3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["student_occurrences", "agenda_items"]
EVENTS = ["occurrence_registered", "agenda_published"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            for event in EVENTS:
                op.execute(f"ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS '{event}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('behavior', 'lateness', 'material', 'health', 'merit', 'other', name='occurrencekind'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='occurrenceseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_occurrences_class_group_id'), 'student_occurrences', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_student_occurrences_institution_id'), 'student_occurrences', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_occurrences_occurred_on'), 'student_occurrences', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_student_occurrences_student_id'), 'student_occurrences', ['student_id'], unique=False)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('homework', 'test', 'event', 'notice', name='agendaitemkind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_class_group_id'), 'agenda_items', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_agenda_items_class_offering_id'), 'agenda_items', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_agenda_items_due_on'), 'agenda_items', ['due_on'], unique=False)
    op.create_index(op.f('ix_agenda_items_institution_id'), 'agenda_items', ['institution_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_items_institution_id'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_due_on'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_class_offering_id'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_class_group_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_student_occurrences_student_id'), table_name='student_occurrences')
    op.drop_index(op.f('ix_student_occurrences_occurred_on'), table_name='student_occurrences')
    op.drop_index(op.f('ix_student_occurrences_institution_id'), table_name='student_occurrences')
    op.drop_index(op.f('ix_student_occurrences_class_group_id'), table_name='student_occurrences')
    op.drop_table('student_occurrences')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ("agendaitemkind", "occurrenceseverity", "occurrencekind"):
            op.execute(f"DROP TYPE IF EXISTS {enum}")
