"""add academic calendar and groups

Revision ID: e4f5a6b7c8da
Revises: d3e4f5a6b7c9
Create Date: 2026-09-30 22:15:00.638550

Fase 12 (entrega 2): periodos letivos, etapas de avaliacao, calendario,
matricula no programa, turmas-grupo e vinculos academicos opcionais em
class_offerings. Novas tabelas recebem a politica `tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f5a6b7c8da'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = [
    "academic_terms",
    "grading_periods",
    "calendar_events",
    "program_enrollments",
    "class_groups",
    "class_group_members",
]
ENUMS = ["termkind", "termstatus", "gradingperiodstatus", "calendareventkind", "programenrollmentstatus", "shift"]
OFFERING_FKS = [
    ("fk_class_offerings_class_group_id", "class_groups", "class_group_id"),
    ("fk_class_offerings_term_id", "academic_terms", "term_id"),
    ("fk_class_offerings_subject_id", "subjects", "subject_id"),
]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('year', 'semester', 'quarter', 'module', name='termkind'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'open', 'closed', name='termstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name')
    )
    op.create_index(op.f('ix_academic_terms_institution_id'), 'academic_terms', ['institution_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('school_day', 'holiday', 'recess', 'exam', 'event', name='calendareventkind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_institution_id'), 'calendar_events', ['institution_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_starts_on'), 'calendar_events', ['starts_on'], unique=False)
    op.create_index(op.f('ix_calendar_events_term_id'), 'calendar_events', ['term_id'], unique=False)
    op.create_table('grading_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='gradingperiodstatus'), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'order')
    )
    op.create_index(op.f('ix_grading_periods_institution_id'), 'grading_periods', ['institution_id'], unique=False)
    op.create_index(op.f('ix_grading_periods_term_id'), 'grading_periods', ['term_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_term_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('shift', sa.Enum('morning', 'afternoon', 'evening', 'full_time', name='shift'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'name')
    )
    op.create_index(op.f('ix_class_groups_homeroom_teacher_id'), 'class_groups', ['homeroom_teacher_id'], unique=False)
    op.create_index(op.f('ix_class_groups_institution_id'), 'class_groups', ['institution_id'], unique=False)
    op.create_index(op.f('ix_class_groups_program_id'), 'class_groups', ['program_id'], unique=False)
    op.create_index(op.f('ix_class_groups_term_id'), 'class_groups', ['term_id'], unique=False)
    op.create_table('program_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('entry_term_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'locked', 'graduated', 'dropped', 'transferred', 'cancelled', name='programenrollmentstatus'), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.ForeignKeyConstraint(['entry_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'registration_number')
    )
    op.create_index(op.f('ix_program_enrollments_curriculum_id'), 'program_enrollments', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_entry_term_id'), 'program_enrollments', ['entry_term_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_institution_id'), 'program_enrollments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_program_id'), 'program_enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_enrollments_student_id'), 'program_enrollments', ['student_id'], unique=False)
    op.create_table('class_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('program_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['program_enrollment_id'], ['program_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_group_id', 'program_enrollment_id')
    )
    op.create_index(op.f('ix_class_group_members_class_group_id'), 'class_group_members', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_class_group_members_institution_id'), 'class_group_members', ['institution_id'], unique=False)
    op.create_index(op.f('ix_class_group_members_program_enrollment_id'), 'class_group_members', ['program_enrollment_id'], unique=False)
    op.add_column('class_offerings', sa.Column('term_id', sa.Integer(), nullable=True))
    op.add_column('class_offerings', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('class_offerings', sa.Column('class_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_class_offerings_class_group_id'), 'class_offerings', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_class_offerings_subject_id'), 'class_offerings', ['subject_id'], unique=False)
    op.create_index(op.f('ix_class_offerings_term_id'), 'class_offerings', ['term_id'], unique=False)
    for name, table, column in OFFERING_FKS:
        op.create_foreign_key(name, 'class_offerings', table, [column], ['id'])
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for name, _table, _column in OFFERING_FKS:
        op.drop_constraint(name, 'class_offerings', type_='foreignkey')
    op.drop_index(op.f('ix_class_offerings_term_id'), table_name='class_offerings')
    op.drop_index(op.f('ix_class_offerings_subject_id'), table_name='class_offerings')
    op.drop_index(op.f('ix_class_offerings_class_group_id'), table_name='class_offerings')
    op.drop_column('class_offerings', 'class_group_id')
    op.drop_column('class_offerings', 'subject_id')
    op.drop_column('class_offerings', 'term_id')
    op.drop_index(op.f('ix_class_group_members_program_enrollment_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_class_group_members_institution_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_class_group_members_class_group_id'), table_name='class_group_members')
    op.drop_table('class_group_members')
    op.drop_index(op.f('ix_program_enrollments_student_id'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_program_id'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_institution_id'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_entry_term_id'), table_name='program_enrollments')
    op.drop_index(op.f('ix_program_enrollments_curriculum_id'), table_name='program_enrollments')
    op.drop_table('program_enrollments')
    op.drop_index(op.f('ix_class_groups_term_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_program_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_institution_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_homeroom_teacher_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_grading_periods_term_id'), table_name='grading_periods')
    op.drop_index(op.f('ix_grading_periods_institution_id'), table_name='grading_periods')
    op.drop_table('grading_periods')
    op.drop_index(op.f('ix_calendar_events_term_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_starts_on'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_institution_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_academic_terms_institution_id'), table_name='academic_terms')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum_name in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
