"""add admissions selection

Revision ID: e6f7a8b9c0d6
Revises: d5e6f7a8b9c5
Create Date: 2026-10-01 02:22:10.175613

Fase 18 (entrega 1): processo seletivo de cursos gratuitos (edital com
reserva de vagas e requisitos, inscricoes com questionario, comprovantes,
classificacao por ordem de inscricao, sorteio ou analise e convocacoes).
Novas tabelas recebem a politica `tenant_isolation`; novo evento
`admission_called`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f7a8b9c0d6'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["admission_calls", "admission_applications", "application_documents"]
ENUMS = ["selectionmethod", "admissioncallstatus", "schooling", "applicationstatus", "seatkind", "documentreview"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'admission_called'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.Enum('first_come', 'lottery', 'review', name='selectionmethod'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('reserved_seats', sa.Integer(), nullable=False),
    sa.Column('reserved_label', sa.String(length=200), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmation_days', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_schooling', sa.Enum('none', 'elementary_incomplete', 'elementary', 'high_school_incomplete', 'high_school', 'higher_incomplete', 'higher', name='schooling'), nullable=True),
    sa.Column('max_income_per_capita_cents', sa.Integer(), nullable=True),
    sa.Column('required_city', sa.String(length=120), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'selected', name='admissioncallstatus'), nullable=False),
    sa.Column('lottery_seed', sa.String(length=64), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_calls_class_offering_id'), 'admission_calls', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_admission_calls_institution_id'), 'admission_calls', ['institution_id'], unique=False)
    op.create_table('admission_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('schooling', sa.Enum('none', 'elementary_incomplete', 'elementary', 'high_school_incomplete', 'high_school', 'higher_incomplete', 'higher', name='schooling'), nullable=False),
    sa.Column('family_income_cents', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('claims_reserved', sa.Boolean(), nullable=False),
    sa.Column('reserved_verified', sa.Boolean(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'ineligible', 'waitlisted', 'selected', 'confirmed', 'declined', 'expired', 'withdrawn', name='applicationstatus'), nullable=False),
    sa.Column('ineligibility_reasons', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('seat_kind', sa.Enum('general', 'reserved', name='seatkind'), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirm_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['admission_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'applicant_id')
    )
    op.create_index(op.f('ix_admission_applications_applicant_id'), 'admission_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_admission_applications_call_id'), 'admission_applications', ['call_id'], unique=False)
    op.create_index(op.f('ix_admission_applications_institution_id'), 'admission_applications', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admission_applications_protocol'), 'admission_applications', ['protocol'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('review', sa.Enum('pending', 'accepted', 'rejected', name='documentreview'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_institution_id'), 'application_documents', ['institution_id'], unique=False)
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_institution_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_admission_applications_protocol'), table_name='admission_applications')
    op.drop_index(op.f('ix_admission_applications_institution_id'), table_name='admission_applications')
    op.drop_index(op.f('ix_admission_applications_call_id'), table_name='admission_applications')
    op.drop_index(op.f('ix_admission_applications_applicant_id'), table_name='admission_applications')
    op.drop_table('admission_applications')
    op.drop_index(op.f('ix_admission_calls_institution_id'), table_name='admission_calls')
    op.drop_index(op.f('ix_admission_calls_class_offering_id'), table_name='admission_calls')
    op.drop_table('admission_calls')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
