"""add assessment and class diary

Revision ID: f5a6b7c8d9eb
Revises: e4f5a6b7c8da
Create Date: 2026-09-30 22:34:20.234390

Fase 13 (entrega 1): esquemas de avaliacao, plano de avaliacoes e notas,
diario de classe com frequencia e esquema de notas opcional na oferta.
Novas tabelas recebem a politica `tenant_isolation`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a6b7c8d9eb'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["grading_schemes", "assessment_items", "grade_entries", "class_diary_entries", "diary_attendance"]
ENUMS = ["gradingscale", "averageformula", "assessmentkind"]
SCHEME_FK = "fk_class_offerings_grading_scheme_id"


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scale', sa.Enum('numeric', 'concept', name='gradingscale'), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('passing_grade', sa.Float(), nullable=False),
    sa.Column('formula', sa.Enum('arithmetic', 'weighted', name='averageformula'), nullable=False),
    sa.Column('recovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_attendance', sa.Float(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name')
    )
    op.create_index(op.f('ix_grading_schemes_institution_id'), 'grading_schemes', ['institution_id'], unique=False)
    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=False),
    sa.Column('grading_period_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('test', 'assignment', 'quiz', 'practical', 'participation', name='assessmentkind'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grading_period_id'], ['grading_periods.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_items_class_offering_id'), 'assessment_items', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_assessment_items_grading_period_id'), 'assessment_items', ['grading_period_id'], unique=False)
    op.create_index(op.f('ix_assessment_items_institution_id'), 'assessment_items', ['institution_id'], unique=False)
    op.create_index(op.f('ix_assessment_items_quiz_id'), 'assessment_items', ['quiz_id'], unique=False)
    op.create_table('class_diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('content_taught', sa.Text(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_meeting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheduled_meeting_id'], ['scheduled_meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_offering_id', 'date')
    )
    op.create_index(op.f('ix_class_diary_entries_class_offering_id'), 'class_diary_entries', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_class_diary_entries_institution_id'), 'class_diary_entries', ['institution_id'], unique=False)
    op.create_index(op.f('ix_class_diary_entries_instructor_id'), 'class_diary_entries', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_class_diary_entries_scheduled_meeting_id'), 'class_diary_entries', ['scheduled_meeting_id'], unique=False)
    op.create_table('grade_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_item_id', sa.Integer(), nullable=False),
    sa.Column('class_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_item_id'], ['assessment_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_item_id', 'class_enrollment_id')
    )
    op.create_index(op.f('ix_grade_entries_assessment_item_id'), 'grade_entries', ['assessment_item_id'], unique=False)
    op.create_index(op.f('ix_grade_entries_class_enrollment_id'), 'grade_entries', ['class_enrollment_id'], unique=False)
    op.create_index(op.f('ix_grade_entries_institution_id'), 'grade_entries', ['institution_id'], unique=False)
    op.create_table('diary_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_entry_id', sa.Integer(), nullable=False),
    sa.Column('class_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('absences', sa.Integer(), nullable=False),
    sa.Column('justified', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['class_diary_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_entry_id', 'class_enrollment_id')
    )
    op.create_index(op.f('ix_diary_attendance_class_enrollment_id'), 'diary_attendance', ['class_enrollment_id'], unique=False)
    op.create_index(op.f('ix_diary_attendance_diary_entry_id'), 'diary_attendance', ['diary_entry_id'], unique=False)
    op.create_index(op.f('ix_diary_attendance_institution_id'), 'diary_attendance', ['institution_id'], unique=False)
    op.add_column('class_offerings', sa.Column('grading_scheme_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_class_offerings_grading_scheme_id'), 'class_offerings', ['grading_scheme_id'], unique=False)
    op.create_foreign_key(SCHEME_FK, 'class_offerings', 'grading_schemes', ['grading_scheme_id'], ['id'])
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(SCHEME_FK, 'class_offerings', type_='foreignkey')
    op.drop_index(op.f('ix_class_offerings_grading_scheme_id'), table_name='class_offerings')
    op.drop_column('class_offerings', 'grading_scheme_id')
    op.drop_index(op.f('ix_diary_attendance_institution_id'), table_name='diary_attendance')
    op.drop_index(op.f('ix_diary_attendance_diary_entry_id'), table_name='diary_attendance')
    op.drop_index(op.f('ix_diary_attendance_class_enrollment_id'), table_name='diary_attendance')
    op.drop_table('diary_attendance')
    op.drop_index(op.f('ix_grade_entries_institution_id'), table_name='grade_entries')
    op.drop_index(op.f('ix_grade_entries_class_enrollment_id'), table_name='grade_entries')
    op.drop_index(op.f('ix_grade_entries_assessment_item_id'), table_name='grade_entries')
    op.drop_table('grade_entries')
    op.drop_index(op.f('ix_class_diary_entries_scheduled_meeting_id'), table_name='class_diary_entries')
    op.drop_index(op.f('ix_class_diary_entries_instructor_id'), table_name='class_diary_entries')
    op.drop_index(op.f('ix_class_diary_entries_institution_id'), table_name='class_diary_entries')
    op.drop_index(op.f('ix_class_diary_entries_class_offering_id'), table_name='class_diary_entries')
    op.drop_table('class_diary_entries')
    op.drop_index(op.f('ix_assessment_items_quiz_id'), table_name='assessment_items')
    op.drop_index(op.f('ix_assessment_items_institution_id'), table_name='assessment_items')
    op.drop_index(op.f('ix_assessment_items_grading_period_id'), table_name='assessment_items')
    op.drop_index(op.f('ix_assessment_items_class_offering_id'), table_name='assessment_items')
    op.drop_table('assessment_items')
    op.drop_index(op.f('ix_grading_schemes_institution_id'), table_name='grading_schemes')
    op.drop_table('grading_schemes')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum_name in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
