"""add social programs and retention

Revision ID: f7a8b9c0d1e7
Revises: e6f7a8b9c0d6
Create Date: 2026-10-01 02:35:12.208524

Fase 18 (entrega 2): financiadores das turmas, beneficios do programa
social (itens, estoque e entregas), limite de faltas da turma e
desligamento da inscricao. Novas tabelas recebem a politica
`tenant_isolation`; novo evento `absence_dismissal`.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a8b9c0d1e7'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

POLICY = "tenant_isolation"
CURRENT = "nullif(current_setting('app.institution_id', true), '')"
CONDITION = f"{CURRENT} IS NULL OR institution_id = {CURRENT}::int"
TABLES = ["funding_sources", "benefit_items", "benefit_stock_entries", "benefit_deliveries"]
ENUMS = ["fundingkind", "benefitkind", "stockorigin"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    if _is_postgres():
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE notificationeventtype ADD VALUE IF NOT EXISTS 'absence_dismissal'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('snack', 'material', 'uniform', 'transport', 'stipend', 'other', name='benefitkind'), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('requires_attendance', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_items_institution_id'), 'benefit_items', ['institution_id'], unique=False)
    op.create_table('funding_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('agreement', 'government', 'system_s', 'parliamentary', 'donation', 'own', 'other', name='fundingkind'), nullable=False),
    sa.Column('agreement_number', sa.String(length=80), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_sources_institution_id'), 'funding_sources', ['institution_id'], unique=False)
    op.create_table('benefit_stock_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('purchase', 'donation', name='stockorigin'), nullable=False),
    sa.Column('funding_source_id', sa.Integer(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_sources.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['benefit_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_stock_entries_funding_source_id'), 'benefit_stock_entries', ['funding_source_id'], unique=False)
    op.create_index(op.f('ix_benefit_stock_entries_institution_id'), 'benefit_stock_entries', ['institution_id'], unique=False)
    op.create_index(op.f('ix_benefit_stock_entries_item_id'), 'benefit_stock_entries', ['item_id'], unique=False)
    op.create_table('benefit_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_offering_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_meeting_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('delivered_on', sa.Date(), nullable=False),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_offering_id'], ['class_offerings.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['benefit_items.id'], ),
    sa.ForeignKeyConstraint(['scheduled_meeting_id'], ['scheduled_meetings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_deliveries_class_offering_id'), 'benefit_deliveries', ['class_offering_id'], unique=False)
    op.create_index(op.f('ix_benefit_deliveries_institution_id'), 'benefit_deliveries', ['institution_id'], unique=False)
    op.create_index(op.f('ix_benefit_deliveries_item_id'), 'benefit_deliveries', ['item_id'], unique=False)
    op.create_index(op.f('ix_benefit_deliveries_scheduled_meeting_id'), 'benefit_deliveries', ['scheduled_meeting_id'], unique=False)
    op.create_index(op.f('ix_benefit_deliveries_student_id'), 'benefit_deliveries', ['student_id'], unique=False)
    op.add_column('class_enrollments', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('class_enrollments', sa.Column('dismissal_reason', sa.String(length=300), nullable=True))
    op.add_column('class_offerings', sa.Column('funding_source_id', sa.Integer(), nullable=True))
    op.add_column('class_offerings', sa.Column('max_absence_percent', sa.Float(), nullable=True))
    op.create_index(op.f('ix_class_offerings_funding_source_id'), 'class_offerings', ['funding_source_id'], unique=False)
    op.create_foreign_key('fk_class_offerings_funding_source_id', 'class_offerings', 'funding_sources', ['funding_source_id'], ['id'])
    # ### end Alembic commands ###

    if _is_postgres():
        for table in TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {POLICY} ON {table} USING ({CONDITION}) WITH CHECK ({CONDITION})")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_class_offerings_funding_source_id', 'class_offerings', type_='foreignkey')
    op.drop_index(op.f('ix_class_offerings_funding_source_id'), table_name='class_offerings')
    op.drop_column('class_offerings', 'max_absence_percent')
    op.drop_column('class_offerings', 'funding_source_id')
    op.drop_column('class_enrollments', 'dismissal_reason')
    op.drop_column('class_enrollments', 'dismissed_at')
    op.drop_index(op.f('ix_benefit_deliveries_student_id'), table_name='benefit_deliveries')
    op.drop_index(op.f('ix_benefit_deliveries_scheduled_meeting_id'), table_name='benefit_deliveries')
    op.drop_index(op.f('ix_benefit_deliveries_item_id'), table_name='benefit_deliveries')
    op.drop_index(op.f('ix_benefit_deliveries_institution_id'), table_name='benefit_deliveries')
    op.drop_index(op.f('ix_benefit_deliveries_class_offering_id'), table_name='benefit_deliveries')
    op.drop_table('benefit_deliveries')
    op.drop_index(op.f('ix_benefit_stock_entries_item_id'), table_name='benefit_stock_entries')
    op.drop_index(op.f('ix_benefit_stock_entries_institution_id'), table_name='benefit_stock_entries')
    op.drop_index(op.f('ix_benefit_stock_entries_funding_source_id'), table_name='benefit_stock_entries')
    op.drop_table('benefit_stock_entries')
    op.drop_index(op.f('ix_funding_sources_institution_id'), table_name='funding_sources')
    op.drop_table('funding_sources')
    op.drop_index(op.f('ix_benefit_items_institution_id'), table_name='benefit_items')
    op.drop_table('benefit_items')
    # ### end Alembic commands ###

    if _is_postgres():
        for enum in ENUMS:
            op.execute(f"DROP TYPE IF EXISTS {enum}")
